# Generated by Django 6.0.3 on 2026-03-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('edited', 'Edited'), ('discarded', 'Discarded'), ('transferred', 'Transferred')], max_length=20)),
                ('original_response', models.TextField()),
                ('final_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='messaging.message')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_evaluations', to='tenants.tenant')),
            ],
        ),
    ]
