# Generated by Django 6.0.3 on 2026-03-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='send_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
