# Generated by Django 6.0.3 on 2026-03-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_review_mode',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('REVIEW', 'Revisão')], default='REVIEW', max_length=20),
        ),
    ]
